[build]
  # Directory with the package.json containing build scripts
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = ".next"
  
  # Default build command
  command = "npm run build"

# Production context: all deploys from the Production branch
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirects for Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Branch deploy context: all deploys that are not from the Production branch
[context.branch-deploy]
  command = "npm run build"

# Deploy Preview context: all Deploy Previews (pull requests)
[context.deploy-preview]
  command = "npm run build"

# Dev context: environment variables for local development
[context.dev.environment]
  NODE_ENV = "development"

# Function settings (if we add Netlify functions later)
[functions]
  directory = "netlify/functions"
